#. programa que calcule dos operandos con los 7 operadores vistos en clase. ¿Cómo puedesforzar que el resultado de la división tenga 2 decimales? 
variable1=int(input("introduce un primer numero: "))
variable2=int(input("introduce un segundo numero: "))
print(variable1+variable2)
print(variable1-variable2)
print(variable1*variable2)
print(variable1/variable2)
print(variable1//variable2)
print(variable1%variable2)
print(variable1**variable2)
